[package]
name = "esdt-contract-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.esdt-contract]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.2"
