// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    esdt_contract
    (
        init => init
        deposit => deposit
        withdraw => withdraw
        safe_batch_transfer_from => safe_batch_transfer_from
        balance_of_batch => balance_of_batch
        set_approval_for_all => set_approval_for_all
        getDeposit => storage
        getApproval => approval
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
